[package]
name = "WSBot"
version = "0.7.0"
authors = ["Sladko"]

[dependencies]
regex = "0.2"
reqwest = "0.9"
lazy_static = "1.0"
mysql = "11.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time = "0.1"
rand = "0.3"

indexmap = "1.0"

native-tls = "0.1"
websocket = "0.20"

net2 = "0.2"